const FRAME_COUNT=5,FRAME_MS=100,$=id=>document.getElementById(id);let frame=0,mouthTimer=null,speechTimer=null,speechDuration=1800,videoQueue=Promise.resolve();
function setStatus(t){$("status").textContent=t}
function showFrame(){$("mira-sprite").style.backgroundPosition=(frame*25)+"% center"}
function stopMouth(){clearInterval(mouthTimer);clearTimeout(speechTimer);mouthTimer=speechTimer=null;frame=0;showFrame();$("speaking-badge").classList.remove("speaking");$("pulse-ring").classList.remove("active")}
function startMouth(){clearInterval(mouthTimer);clearTimeout(speechTimer);$("speaking-badge").classList.add("speaking");$("pulse-ring").classList.add("active");frame=0;showFrame();mouthTimer=setInterval(()=>{frame=(frame+1)%FRAME_COUNT;showFrame()},FRAME_MS);speechTimer=setTimeout(stopMouth,speechDuration)}
function addMessage(who,text){if(!text)return;const box=$("messages"),b=document.createElement("div");b.className="bubble "+(who==="Mira"?"mira-bubble":"user-bubble");const n=document.createElement("div");n.className="bubble-name";n.textContent=who;b.append(n,document.createTextNode(text));box.appendChild(b);box.scrollTop=box.scrollHeight}
async function makeVideo(text){if(!text?.trim())return;try{ $("video-status").textContent="Generating…";const r=await fetch("/api/video",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})});const j=await r.json();if(!r.ok)throw Error(j.error||"Video generation failed");if(j.url){$("mira-video").src=j.url;$("mira-video").classList.remove("hidden");$("video-status").textContent="Speaking";$("mira-video").play().catch(()=>{})}else $("video-status").textContent="Speaking"}catch(e){console.error(e);$("video-status").textContent="Voice ready"}}
function enqueueVideo(t){videoQueue=videoQueue.then(()=>makeVideo(t)).catch(console.error)}
async function startMira(){try{const c=await fetch("/api/config").then(r=>r.json());if(!c.ready){$("setup").classList.remove("hidden");setStatus("Setup needed");return}if(!window.DeepgramAgent){setStatus("Voice unavailable");return}setStatus("Ready");window.DeepgramAgent.init({tokenFactory:()=>fetch("/api/deepgram-token").then(async r=>{if(!r.ok)throw Error(await r.text());return r.text()}),agent:{language:"en",listen:{provider:{type:"deepgram",version:"v2",model:"flux-general-en"}},think:{provider:{type:"open_ai",model:"gpt-4o-mini",temperature:.8},prompt:"You are Mira, a warm gothic AI companion. Speak naturally and conversationally. Keep spoken replies concise. No markdown or stage directions."},speak:{provider:{type:"deepgram",version:"v1",model:"aura-2-amalthea-en",speed:1}}},layout:"button",buttonId:"mira-talk-button",showTranscript:false,showMicToggle:true,showSpeakerToggle:true,showTextInput:true,vad:true,colorScheme:"dark",text:{name:"Mira",startLabel:"Talk to Mira",stopLabel:"End conversation",connectingLabel:"Connecting…",inputPlaceholder:"Talk to Mira…",emptyStateHint:"Press start to begin talking."},overrides:{systemPrompt:"You are Mira, a warm gothic AI companion. Speak naturally and conversationally. Keep spoken replies concise. No markdown or stage directions.",greeting:"Hi, I’m Mira. It’s nice to hear your voice."},on:{onConnect:()=>setStatus("Listening"),onDisconnect:()=>{stopMouth();setStatus("Ready")},onError:e=>{console.error(e);stopMouth();setStatus("Voice error")},onAgentError:e=>{console.error(e);stopMouth();setStatus("Agent error")},onMessage:m=>{if(!m?.content)return;if(m.role==="user")addMessage("You",m.content);else if(m.role==="assistant"){addMessage("Mira",m.content);const words=m.content.trim().split(/\s+/).filter(Boolean).length;speechDuration=Math.max(1200,Math.min(14000,words*320));enqueueVideo(m.content)}},onAgentStartedSpeaking:()=>{setStatus("Mira is speaking");startMouth()}}})}catch(e){console.error(e);setStatus("Connection error")}}
$("save-key").onclick=async()=>{const key=$("deepgram-key").value.trim();if(!key)return;try{const r=await fetch("/api/setup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({deepgramApiKey:key})});if(!r.ok)throw Error("Setup failed");location.reload()}catch(e){alert(e.message)}};
$("clear-chat").onclick=()=>{$("messages").innerHTML='<div class="bubble mira-bubble"><div class="bubble-name">Mira</div><span>Conversation cleared. I’m still here.</span></div>'};
$("settings-btn").onclick=()=>{$("setup").classList.toggle("hidden")};
$("nav-settings").onclick=()=>{$("setup").classList.remove("hidden")};
$("nav-chat").onclick=()=>{$("setup").classList.add("hidden")};
$("mira-video").onended=()=>{$("mira-video").classList.add("hidden");$("mira-video").removeAttribute("src");$("video-status").textContent="Ready"};
showFrame();startMira();