using System.Text;using System.Text.Json;using System.Text.Json.Nodes;
var builder=WebApplication.CreateBuilder(args);var app=builder.Build();app.Urls.Add("http://127.0.0.1:8787");
var root=AppContext.BaseDirectory;var dir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Mira");Directory.CreateDirectory(dir);var file=Path.Combine(dir,"config.json");
JsonObject C(){try{return JsonNode.Parse(File.ReadAllText(file))?.AsObject()??new JsonObject();}catch{return new JsonObject();}}
void Save(JsonObject o)=>File.WriteAllText(file,o.ToJsonString(new JsonSerializerOptions{WriteIndented=true}));
app.MapGet("/api/config",()=>{var c=C();return Results.Json(new{ready=!string.IsNullOrWhiteSpace(c["deepgramApiKey"]?.ToString())&&!string.IsNullOrWhiteSpace(c["agentId"]?.ToString()),agentId=c["agentId"]?.ToString()});});
app.MapPost("/api/setup",async(HttpRequest q)=>{var b=await JsonSerializer.DeserializeAsync<JsonObject>(q.Body);if(b==null)return Results.BadRequest(new{error="Invalid setup"});var c=C();c["deepgramApiKey"]=b["deepgramApiKey"]?.ToString();c["agentId"]=b["deepgramAgentId"]?.ToString();c["falKey"]=b["falKey"]?.ToString();Save(c);return Results.Ok(new{ok=true});});
app.MapGet("/api/deepgram-token",async()=>{var k=C()["deepgramApiKey"]?.ToString();if(string.IsNullOrWhiteSpace(k))return Results.BadRequest(new{error="Deepgram key missing"});using var h=new HttpClient();h.DefaultRequestHeaders.Authorization=new System.Net.Http.Headers.AuthenticationHeaderValue("Token",k);var r=await h.PostAsync("https://api.deepgram.com/v1/auth/grant",new StringContent("{\"ttl_seconds\":300}",Encoding.UTF8,"application/json"));var s=await r.Content.ReadAsStringAsync();if(!r.IsSuccessStatusCode)return Results.StatusCode((int)r.StatusCode);try{return Results.Text(JsonNode.Parse(s)?["access_token"]?.ToString()??s,"text/plain");}catch{return Results.Text(s,"text/plain");}});
app.MapPost("/api/video",async()=>{var k=C()["falKey"]?.ToString();if(string.IsNullOrWhiteSpace(k))return Results.BadRequest(new{error="fal.ai key missing"});var img=Path.Combine(root,"luna mouth closed.png");if(!File.Exists(img))return Results.NotFound(new{error="Mira image missing"});var data="data:image/png;base64,"+Convert.ToBase64String(await File.ReadAllBytesAsync(img));using var h=new HttpClient();h.DefaultRequestHeaders.Authorization=new System.Net.Http.Headers.AuthenticationHeaderValue("Key",k);var p=new JsonObject{{"prompt","Mira gently talks directly to the camera. Natural blinking, subtle head movement, soft breathing, stable face and identity, gothic romantic atmosphere, cinematic realistic motion."},{"start_image_url",data},{"duration","5"},{"generate_audio",false}};var r=await h.PostAsync("https://queue.fal.run/fal-ai/kling-video/v3/standard/image-to-video",new StringContent(p.ToJsonString(),Encoding.UTF8,"application/json"));var s=await r.Content.ReadAsStringAsync();if(!r.IsSuccessStatusCode)return Results.StatusCode((int)r.StatusCode);var id=JsonNode.Parse(s)?["request_id"]?.ToString();if(string.IsNullOrWhiteSpace(id))return Results.BadRequest(new{error="fal queue did not return request id"});for(var i=0;i<90;i++){await Task.Delay(2000);var sr=await h.GetAsync("https://queue.fal.run/fal-ai/kling-video/v3/standard/image-to-video/requests/"+id+"/status");var ss=await sr.Content.ReadAsStringAsync();if(ss.Contains("COMPLETED")){var rr=await h.GetAsync("https://queue.fal.run/fal-ai/kling-video/v3/standard/image-to-video/requests/"+id);var rs=await rr.Content.ReadAsStringAsync();var u=JsonNode.Parse(rs)?["video"]?["url"]?.ToString();if(u!=null)return Results.Ok(new{url=u});}if(ss.Contains("FAILED"))break;}return Results.Problem("fal.ai video failed or timed out");});
app.MapGet("/api/health",()=>Results.Ok(new{ok=true}));
app.MapFallback(async ctx=>{var rel=(ctx.Request.Path.Value??"/").TrimStart('/');if(rel=="")rel="index.html";var full=Path.GetFullPath(Path.Combine(root,rel.Replace('/','\\')));if(!full.StartsWith(Path.GetFullPath(root),StringComparison.OrdinalIgnoreCase)||!File.Exists(full)){ctx.Response.StatusCode=404;return;}ctx.Response.ContentType=Path.GetExtension(full).ToLowerInvariant() switch{".html"=>"text/html",".png"=>"image/png",".css"=>"text/css",".js"=>"text/javascript",_=>"application/octet-stream"};await ctx.Response.SendFileAsync(full);});
app.Run();